// Comprehensive RMM (roundTiesToAway) vector generator using MPFR as an
// independent oracle. Ties-away is built from directed rounding + exact
// midpoint comparison (MPFR has no native ties-away mode).
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <mpfr.h>

enum { OP_ADD, OP_SUB, OP_MUL, OP_DIV, OP_SQRT };
static const char* OPN[] = {"ADD","SUB","MUL","DIV","SQRT"};

#define WP 256  // working precision: exact for +,-,* and faithful for /,sqrt

// Round high-precision x to `prec`-bit target with ties-away, into out.
static void round_ties_away(mpfr_t out, mpfr_srcptr x, mpfr_prec_t prec) {
    if (mpfr_nan_p(x) || mpfr_inf_p(x) || mpfr_zero_p(x)) { mpfr_set(out, x, MPFR_RNDN); return; }
    mpfr_t lo, hi, mid;
    mpfr_init2(lo, prec); mpfr_init2(hi, prec); mpfr_init2(mid, WP + 8);
    mpfr_set(lo, x, MPFR_RNDD);
    mpfr_set(hi, x, MPFR_RNDU);
    if (mpfr_equal_p(lo, hi)) { mpfr_set(out, lo, MPFR_RNDN); }  // exact
    else {
        mpfr_add(mid, lo, hi, MPFR_RNDN); mpfr_div_2ui(mid, mid, 1, MPFR_RNDN); // exact midpoint
        int c = mpfr_cmp(x, mid);
        if (c > 0)       mpfr_set(out, hi, MPFR_RNDN);
        else if (c < 0)  mpfr_set(out, lo, MPFR_RNDN);
        else { // exact tie -> larger magnitude
            if (mpfr_cmpabs(hi, lo) >= 0) mpfr_set(out, hi, MPFR_RNDN);
            else mpfr_set(out, lo, MPFR_RNDN);
        }
    }
    mpfr_clears(lo, hi, mid, (mpfr_ptr)0);
}

static void compute(mpfr_t r, int op, mpfr_srcptr a, mpfr_srcptr b) {
    switch (op) {
        case OP_ADD: mpfr_add(r, a, b, MPFR_RNDN); break;
        case OP_SUB: mpfr_sub(r, a, b, MPFR_RNDN); break;
        case OP_MUL: mpfr_mul(r, a, b, MPFR_RNDN); break;
        case OP_DIV: mpfr_div(r, a, b, MPFR_RNDN); break;
        case OP_SQRT: mpfr_sqrt(r, a, MPFR_RNDN); break;
    }
}

static void emit32(int op, uint32_t ab, uint32_t bb) {
    float af, bf; memcpy(&af,&ab,4); memcpy(&bf,&bb,4);
    mpfr_t a,b,r,o; mpfr_init2(a,WP);mpfr_init2(b,WP);mpfr_init2(r,WP);mpfr_init2(o,24);
    mpfr_set_flt(a, af, MPFR_RNDN); mpfr_set_flt(b, bf, MPFR_RNDN);
    compute(r, op, a, b);
    round_ties_away(o, r, 24);
    float wf = mpfr_get_flt(o, MPFR_RNDN); uint32_t wb; memcpy(&wb,&wf,4);
    printf("  {0, OP_%s, 0x%08xULL, 0x%08xULL, 0x%08xULL},\n", OPN[op], ab, bb, wb);
    mpfr_clears(a,b,r,o,(mpfr_ptr)0);
}
static void emit64(int op, uint64_t ab, uint64_t bb) {
    double af, bf; memcpy(&af,&ab,8); memcpy(&bf,&bb,8);
    mpfr_t a,b,r,o; mpfr_init2(a,WP);mpfr_init2(b,WP);mpfr_init2(r,WP);mpfr_init2(o,53);
    mpfr_set_d(a, af, MPFR_RNDN); mpfr_set_d(b, bf, MPFR_RNDN);
    compute(r, op, a, b);
    round_ties_away(o, r, 53);
    double wf = mpfr_get_d(o, MPFR_RNDN); uint64_t wb; memcpy(&wb,&wf,8);
    printf("  {1, OP_%s, 0x%016llxULL, 0x%016llxULL, 0x%016llxULL},\n", OPN[op], (unsigned long long)ab,(unsigned long long)bb,(unsigned long long)wb);
    mpfr_clears(a,b,r,o,(mpfr_ptr)0);
}

// xorshift for reproducible pseudo-random bit patterns
static uint64_t st = 0x123456789abcdef0ULL;
static uint64_t xs(void){ st^=st<<13; st^=st>>7; st^=st<<17; return st; }

int main(void){
    printf("// auto-generated by gen_mpfr.c — RMM roundTiesToAway oracle (MPFR)\n");
    printf("static const rmm_vec_t VECS[] = {\n");
    // Targeted f32 edge cases around 1.0/2.0 ties (1/4,1/2,3/4 ulp)
    uint32_t one=0x3f800000, two=0x40000000;
    for (int k=-26;k<=-22;k++){ uint32_t e=(uint32_t)(127+k)<<23; emit32(OP_ADD, one, e); emit32(OP_ADD, two, e); emit32(OP_SUB, one, e|0x80000000); }
    // Random f32 across all ops
    for (int i=0;i<400;i++){
        uint32_t a=(uint32_t)xs(), b=(uint32_t)xs();
        // bias exponents into a sane finite range to exercise rounding (avoid mostly-inf/nan)
        a=(a&0x807fffff)|((uint32_t)(60+(xs()%80))<<23);
        b=(b&0x807fffff)|((uint32_t)(60+(xs()%80))<<23);
        int op=i%4; emit32(op,a,b);
        if(i%3==0){ uint32_t s=a&0x7fffffff; emit32(OP_SQRT,s,0);} 
    }
    // Random f64 across all ops
    for (int i=0;i<400;i++){
        uint64_t a=xs(), b=xs();
        a=(a&0x800fffffffffffffULL)|((uint64_t)(0x3c0+(xs()%0x80))<<52);
        b=(b&0x800fffffffffffffULL)|((uint64_t)(0x3c0+(xs()%0x80))<<52);
        int op=i%4; emit64(op,a,b);
        if(i%3==0){ uint64_t s=a&0x7fffffffffffffffULL; emit64(OP_SQRT,s,0);} 
    }

    // Subnormal + normal/subnormal boundary ties (f32): exp in [0..3]
    for (int k=0;k<4;k++){ uint32_t e=(uint32_t)k<<23;
        emit32(OP_ADD, 0x00000001u|e, 0x00000001u);     // tiny + tiny
        emit32(OP_ADD, 0x007fffffu, 0x00000001u|e);     // max subnormal boundary
        emit32(OP_ADD, 0x00800000u, 0x00000001u);       // smallest normal + 1
        emit32(OP_SUB, 0x00800000u, 0x00000001u);       // boundary crossing down
        emit32(OP_MUL, 0x00000003u, 0x3f000000u|e);     // subnormal * ~0.5
    }
    // Random subnormal-range f32 (exp 0..8) across ops
    for (int i=0;i<200;i++){ uint32_t a=(uint32_t)xs()&0x807fffff, b=(uint32_t)xs()&0x807fffff;
        a|=((uint32_t)(xs()%9)<<23); b|=((uint32_t)(xs()%9)<<23);
        emit32(i%3, a, b); }
    // Random subnormal-range f64 (exp 0..10) across ops
    for (int i=0;i<200;i++){ uint64_t a=xs()&0x800fffffffffffffULL, b=xs()&0x800fffffffffffffULL;
        a|=((uint64_t)(xs()%11)<<52); b|=((uint64_t)(xs()%11)<<52);
        emit64(i%3, a, b); }
    printf("};\n");
    return 0;
}
