/* rmm-test — reproducer + regression harness for RVVM issue #204:
 * the RMM rounding mode (IEEE-754 roundTiesToAway) was emulated as
 * "always round away from zero", correct only on exact ties.
 *
 * Each vector runs an FP op under frm=RMM (set with fsrmi 4) using a
 * DYN-rounding instruction, matching how the issue reproduces (RVVM keys
 * RMM off the dynamic frm CSR, not the static rm field). Expected values
 * come from vectors.inc, generated by tools/gen_mpfr.c using MPFR as an
 * independent roundTiesToAway oracle (all 5 ops, f32 + f64).
 *
 *   nix shell nixpkgs#llvmPackages.bintools -c make   # from this dir
 *   make run RVVM=/path/to/rvvm
 */
#include <stdint.h>

#include "uart.h"
#include "fdt.h"
#include "panic.h"

enum { OP_ADD, OP_SUB, OP_MUL, OP_DIV, OP_SQRT };

typedef struct {
    int      type;  /* 0 = f32, 1 = f64 */
    int      op;
    uint64_t a;
    uint64_t b;
    uint64_t want;
} rmm_vec_t;

#include "vectors.inc"

static inline float    u2f(uint32_t u) { float f;  __builtin_memcpy(&f, &u, 4); return f; }
static inline uint32_t f2u(float f)    { uint32_t u; __builtin_memcpy(&u, &f, 4); return u; }
static inline double   u2d(uint64_t u) { double d; __builtin_memcpy(&d, &u, 8); return d; }
static inline uint64_t d2u(double d)   { uint64_t u; __builtin_memcpy(&u, &d, 8); return u; }

/* Each op forces frm=RMM (fsrmi 4) then runs a DYN-rounding instruction. */
static uint32_t run32(int op, float a, float b) {
    float r;
    switch (op) {
        case OP_ADD:  __asm__ volatile("fsrmi 4\n\tfadd.s %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_SUB:  __asm__ volatile("fsrmi 4\n\tfsub.s %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_MUL:  __asm__ volatile("fsrmi 4\n\tfmul.s %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_DIV:  __asm__ volatile("fsrmi 4\n\tfdiv.s %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        default:      __asm__ volatile("fsrmi 4\n\tfsqrt.s %0,%1"   : "=f"(r) : "f"(a));         break;
    }
    return f2u(r);
}

static uint64_t run64(int op, double a, double b) {
    double r;
    switch (op) {
        case OP_ADD:  __asm__ volatile("fsrmi 4\n\tfadd.d %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_SUB:  __asm__ volatile("fsrmi 4\n\tfsub.d %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_MUL:  __asm__ volatile("fsrmi 4\n\tfmul.d %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_DIV:  __asm__ volatile("fsrmi 4\n\tfdiv.d %0,%1,%2" : "=f"(r) : "f"(a), "f"(b)); break;
        default:      __asm__ volatile("fsrmi 4\n\tfsqrt.d %0,%1"   : "=f"(r) : "f"(a));         break;
    }
    return d2u(r);
}

/* Static RMM: frm forced to RNE (fsrmi 0), rounding selected by the instruction's
 * `,rmm` suffix. Verifies the static rm path and that it overrides a non-RMM frm. */
static uint32_t run32_static(int op, float a, float b) {
    float r;
    switch (op) {
        case OP_ADD:  __asm__ volatile("fsrmi 0\n\tfadd.s %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_SUB:  __asm__ volatile("fsrmi 0\n\tfsub.s %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_MUL:  __asm__ volatile("fsrmi 0\n\tfmul.s %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_DIV:  __asm__ volatile("fsrmi 0\n\tfdiv.s %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        default:      __asm__ volatile("fsrmi 0\n\tfsqrt.s %0,%1,rmm"   : "=f"(r) : "f"(a));         break;
    }
    return f2u(r);
}
static uint64_t run64_static(int op, double a, double b) {
    double r;
    switch (op) {
        case OP_ADD:  __asm__ volatile("fsrmi 0\n\tfadd.d %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_SUB:  __asm__ volatile("fsrmi 0\n\tfsub.d %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_MUL:  __asm__ volatile("fsrmi 0\n\tfmul.d %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        case OP_DIV:  __asm__ volatile("fsrmi 0\n\tfdiv.d %0,%1,%2,rmm" : "=f"(r) : "f"(a), "f"(b)); break;
        default:      __asm__ volatile("fsrmi 0\n\tfsqrt.d %0,%1,rmm"   : "=f"(r) : "f"(a));         break;
    }
    return d2u(r);
}

/* Static `,rmm` while frm is a *directed* mode (RTZ): the op must still round
 * ties-away, and the following dynamic op must still see RTZ (host mode restored).
 * a=1.0, b=1.5*2^-24 -> exact 1 + 0.75 ulp: nearest/away rounds up, RTZ truncates.
 * Returns 0 on success. */
static int restore_check(void) {
    int fails = 0;
    const float a = u2f(0x3f800000), b = u2f(0x33c00000);
    float rmm, rtz;
    __asm__ volatile("fsrmi 1\n\tfadd.s %0,%1,%2,rmm" : "=f"(rmm) : "f"(a), "f"(b)); /* static RMM under frm=RTZ */
    __asm__ volatile("fadd.s %0,%1,%2"               : "=f"(rtz) : "f"(a), "f"(b)); /* DYN -> should be RTZ */
    if (f2u(rmm) != 0x3f800001) { uart_printf("FAIL restore: static-rmm got %x want 3f800001\n", f2u(rmm)); fails++; }
    if (f2u(rtz) != 0x3f800000) { uart_printf("FAIL restore: frm not restored, dyn got %x want 3f800000\n", f2u(rtz)); fails++; }
    __asm__ volatile("fsrmi 0"); /* leave frm at RNE */
    return fails;
}

static const char *opname(int op) {
    static const char *n[] = {"add", "sub", "mul", "div", "sqrt"};
    return n[op];
}

void kmain(uint64_t hartid, uint64_t fdt_addr) {
    uart_init(0);
    fdt_t fdt;
    if (fdt_init(&fdt, (const void *)(uintptr_t)fdt_addr)) {
        uint32_t off = fdt_find_compatible(&fdt, "ns16550a");
        uint64_t at = 0;
        if (fdt_node_reg64(&fdt, off, 0, &at, NULL)) uart_init((uintptr_t)at);
    }
    (void)hartid;

    uart_puts("\n=== rmm-test (issue #204: RMM roundTiesToAway, MPFR oracle) ===\n");

    unsigned n = sizeof(VECS) / sizeof(VECS[0]);
    unsigned pass = 0, fail = 0;
    for (unsigned i = 0; i < n; i++) {
        const rmm_vec_t *v = &VECS[i];
        /* Each vector is checked twice: dynamic frm=RMM and static `,rmm` suffix. */
        uint64_t dyn, sta;
        if (v->type == 0) {
            dyn = run32(v->op, u2f((uint32_t)v->a), u2f((uint32_t)v->b));
            sta = run32_static(v->op, u2f((uint32_t)v->a), u2f((uint32_t)v->b));
        } else {
            dyn = run64(v->op, u2d(v->a), u2d(v->b));
            sta = run64_static(v->op, u2d(v->a), u2d(v->b));
        }
        for (int s = 0; s < 2; s++) {
            uint64_t got = s ? sta : dyn;
            if (got == v->want) {
                pass++;
            } else {
                fail++;
                uart_printf("FAIL #%u %s %s%s a=%x b=%x got=%x want=%x\n",
                            i, s ? "static" : "dyn", opname(v->op), v->type ? ".d" : ".s",
                            (uint32_t)v->a, (uint32_t)v->b, (uint32_t)got, (uint32_t)v->want);
            }
        }
    }

    unsigned restore_fails = restore_check();
    fail += restore_fails;

    uart_printf("\nRMM-RESULT pass=%u fail=%u (vectors=%u x2 dyn+static, restore_fails=%u)\n",
                pass, fail, n, restore_fails);
    hal_exit(fail == 0 ? 0 : 1);
}
